# Generate fixed decoding and CTYPE1 data on Windows; no game files are read.
$ErrorActionPreference = 'Stop'
$codec = [Text.Encoding]::GetEncoding(932, [Text.EncoderFallback]::ExceptionFallback, [Text.DecoderFallback]::ExceptionFallback)
Add-Type -TypeDefinition @'
using System;
using System.Runtime.InteropServices;
public static class Cp932Types {
    [DllImport("kernel32.dll", CharSet=CharSet.Unicode, SetLastError=true)]
    public static extern bool GetStringTypeW(uint kind, string text, int count, [Out] ushort[] types);
}
'@
$single = [Collections.Generic.List[UInt16]]::new()
$pairs = [Collections.Generic.List[UInt16]]::new()
$units = [Collections.Generic.SortedSet[UInt16]]::new()
function Decode-Unit([byte[]] $sequence) {
    try {
        $text = $codec.GetString($sequence)
        if ($text.Length -eq 1) { return [UInt16][char]$text[0] }
    } catch [Text.DecoderFallbackException] { }
    return [UInt16]0xFFFF
}
for ($b=0; $b -lt 256; $b++) {
    $unit = Decode-Unit ([byte[]]@($b))
    $single.Add($unit)
    if ($unit -ne 0xFFFF) { [void]$units.Add($unit) }
}
foreach ($lead in @((0x81..0x9F) + (0xE0..0xFC))) {
    foreach ($trail in @((0x40..0x7E) + (0x80..0xFC))) {
        $unit = Decode-Unit ([byte[]]@($lead,$trail))
        $pairs.Add($unit)
        if ($unit -ne 0xFFFF) { [void]$units.Add($unit) }
    }
}
$chars = [char[]]@($units | ForEach-Object { [char]$_ })
$types = [UInt16[]]::new($chars.Length)
if (-not [Cp932Types]::GetStringTypeW(1, [string]::new($chars), $chars.Length, $types)) { throw 'GetStringTypeW generation failed' }
$out = [Text.StringBuilder]::new()
[void]$out.AppendLine('// Generated by tools/generate_cp932_table.ps1 on Windows.')
[void]$out.AppendLine('// CP932 decoder: .NET exception fallback; CTYPE1: native Windows API.')
[void]$out.AppendLine('// Host: ' + [Environment]::OSVersion.VersionString)
[void]$out.AppendLine('#pragma once')
[void]$out.AppendLine('#include <cstdint>')
function Append-Array($name, $values) {
    [void]$out.AppendLine('inline constexpr uint16_t ' + $name + '[] = {')
    for ($i=0; $i -lt $values.Count; $i+=12) {
        $row = for ($j=$i; $j -lt [Math]::Min($i+12,$values.Count); $j++) { '0x{0:X4}' -f $values[$j] }
        [void]$out.AppendLine('    ' + ($row -join ', ') + ',')
    }
    [void]$out.AppendLine('};')
}
Append-Array 'kCp932Single' $single
Append-Array 'kCp932Pairs' $pairs
[void]$out.AppendLine('struct Cp932Type { uint16_t unit, flags; };')
[void]$out.AppendLine('inline constexpr Cp932Type kCp932Types[] = {')
for ($i=0; $i -lt $chars.Length; $i++) { [void]$out.AppendLine(('    {{0x{0:X4}, 0x{1:X4}}},' -f [UInt16]$chars[$i], $types[$i])) }
[void]$out.AppendLine('};')
$target = Join-Path $PSScriptRoot '../vita/src/cp932_data.h'
[IO.File]::WriteAllText($target, $out.ToString().Replace("`r`n", "`n"), [Text.UTF8Encoding]::new($false))
Write-Output ('Generated CP932 data: {0} pair slots, {1} classified Unicode units' -f $pairs.Count, $chars.Length)
